### ISSUE TITLE
ISO8583 Bitmap issue

### ISSUE THREAD

**Issue by vamsikiranreddygithub** [tilln/jmeter-iso8583#36] opened 2021-02-25 08:41 UTC
Hi Tilln,

We have configured Jmeter with the xml configuration file and placed in bin folder.
When configured with ISO8583 message in jmeter and submit the request, the bitmap is not converting correctly.
Attaching the log from Jmeter below.
2021-02-25 13:49:20,217 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2021-02-25 13:49:20,217 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2021-02-25 13:49:20,217 DEBUG n.c.b.j.i.ISO8583Config: Creating Q2
2021-02-25 13:49:20,233 INFO n.c.b.j.i.Q2: (Q2.system) Q2 started, deployDir=E:\jmeter\apache-jmeter-5.1.1\apache-jmeter-5.1.1\bin\deploy, environment=default
2021-02-25 13:49:20,233 DEBUG n.c.b.j.i.Q2: (Q2.system) [version] jPOS 2.1.4 master/6225824 (2020-03-31 18:07:15 UYT) 

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

jPOS Community Edition, licensed under GNU AGPL v3.0.
This software is probably not suitable for commercial use.
Please see http://jpos.org/license for details.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.9 (Darwin)

iQEcBAEBAgAGBQJMolHDAAoJEOQyeO71nYtFv74H/3OgehDGEy1VXp2U3/GcAobg
HH2eZjPUz53r38ARPiU3pzm9LwDa3WZgJJaa/b9VrJwKvbPwe9+0kY3gScDE1skT
ladHt+KHHmGQArEutkzHlpZa73RbroFEIa1qmN6MaDEHGoxZqDh0Sv2cpvOaVYGO
St8ZaddLBPC17bSjAPWo9sWbvL7FgPFOHhnPmbeux8SLtnfWxXWsgo5hLBanKmO1
1z+I/w/6DL6ZYZU6bAJUk+eyVVImJqw0x3IEElI07Nh9MC6BA4iJ77ejobj8HI2r
q9ulRPEqH9NR79619lNKVUkE206dVlXo7xHmJS1QZy5v/GT66xBxyDVfTduPFXk=
=oP+v
-----END PGP SIGNATURE-----

2021-02-25 13:49:20,248 DEBUG n.c.b.j.i.ISO8583Config: 'ISO8583 Connection Configuration' setting up QBeans jmeter-4f9f9226
2021-02-25 13:49:20,248 DEBUG n.c.b.j.i.ISO8583Config: Deploying <channel-adaptor name="jmeter-4f9f9226-channel" logger="Q2"><in>jmeter-4f9f9226-send</in><out>jmeter-4f9f9226-receive</out><reconnect-delay>10000</reconnect-delay><wait-for-workers-on-stop>yes</wait-for-workers-on-stop><channel name="jmeter-4f9f9226" class="org.jpos.iso.channel.ASCIIChannel" packager="org.jpos.iso.packager.GenericPackager" header="" logger="Q2"><property name="packager-config" value="E:/jmeter/ISOXML/iso87ascii.xml" /><property name="host" value="10.51.27.122" /><property name="port" value="30122" /></channel></channel-adaptor>
2021-02-25 13:49:20,264 DEBUG n.c.b.j.i.ISO8583Config: Deploying <qmux name="jmeter-4f9f9226-mux" logger="Q2"><in>jmeter-4f9f9226-receive</in><out>jmeter-4f9f9226-send</out><unhandled>jmeter-4f9f9226-unhandled</unhandled><ready>jmeter-4f9f9226.ready</ready><key>11</key></qmux>
2021-02-25 13:49:20,264 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true, *local*)
2021-02-25 13:49:20,514 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2021-02-25 13:49:20,514 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2021-02-25 13:49:20,514 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2021-02-25 13:49:20,514 DEBUG n.c.b.j.i.Q2: (channel/10.51.27.122:30122) [connect] Try 0 10.51.27.122:30122
2021-02-25 13:49:20,514 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2021-02-25 13:49:20,530 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2021-02-25 13:49:20,530 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2021-02-25 13:49:20,530 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2021-02-25 13:49:20,530 INFO o.a.j.u.BeanShellTestElement: 144959378033
2021-02-25 13:49:20,530 DEBUG n.c.b.j.i.ISO8583Sampler: Applying config 'ISO8583 Connection Configuration'
2021-02-25 13:49:20,530 DEBUG n.c.b.j.i.ISO8583Config: Creating packager from 'E:/jmeter/ISOXML/iso87ascii.xml'
2021-02-25 13:49:20,545 DEBUG n.c.b.j.i.ISO8583Sampler: sampleStart
2021-02-25 13:49:20,545 DEBUG n.c.b.j.i.Q2: (channel/10.51.27.122:30122) [send] Out: 0200 000459 BOS43210
2021-02-25 13:50:20,546 DEBUG n.c.b.j.i.ISO8583Sampler: sampleEnd
2021-02-25 13:50:20,546 DEBUG n.c.b.j.i.ISO8583Sampler: Packed request '30323030f238448108e08000000000000400010031393131303730303130303935353134353730373639303030303030303030303030303130303030323235313334393230303030343539313334393230303232353438313430313930353036313131313036313434393539333738303333424f533433323130424f53393139383736353433323130424f53535054412020202020202020202020202020202020204d4f4239383736353433323130494e333536313231313938373635343332313030383730303130303234353030323030334d4f423034353031314e504349424f535350324130343930303331323330353030313731313036303031393837363534333231303035313030365032414d4f423035363030334d4f42'
2021-02-25 13:50:20,546 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2021-02-25 13:50:20,546 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2021-02-25 13:50:20,546 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2021-02-25 13:50:20,546 DEBUG n.c.b.j.i.ISO8583Config: Shutting down QBeans
2021-02-25 13:50:20,546 DEBUG n.c.b.j.i.ISO8583Config: Undeploying jmeter-4f9f9226-mux
2021-02-25 13:50:20,561 DEBUG n.c.b.j.i.ISO8583Config: Undeploying jmeter-4f9f9226-channel
2021-02-25 13:50:20,561 INFO n.c.b.j.i.Q2: (Q2.system) shutting down
2021-02-25 13:50:20,577 INFO n.c.b.j.i.Q2: (Q2.system) shutdown done
2021-02-25 13:50:20,577 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)

ALso, below is the message configuration in Jmeter.
<isomsg direction="outgoing">
  
  <field id="0" value="0200"/>
  <field id="2" value="1107001009551457076"/>
  <field id="3" value="900000"/>
  <field id="4" value="000000001000"/>
  <field id="7" value="0225134920"/>
  <field id="11" value="000459"/>
  <field id="12" value="134920"/>
  <field id="13" value="0225"/>
  <field id="18" value="4814"/>
  <field id="22" value="019"/>
  <field id="25" value="05"/>
  <field id="32" value="111106"/>
  <field id="37" value="144959378033"/>
  <field id="41" value="BOS43210"/>
  <field id="42" value="BOS919876543210"/>
  <field id="43" value="BOSSPTA                  MOB9876543210IN"/>
  <field id="49" value="356"/>
  <field id="102" value="119876543210"/>
  <field id="120" value="00100245002003MOB045011NPCIBOSSP2A04900312305001711060019876543210051006P2AMOB056003MOB"/>
</isomsg>

**Comment by tilln** [comment] 2021-02-25 08:51
Hi @vamsikiranreddygithub 

Please provide some more details on 
> the bitmap is not converting correctly.

As I don't see JMeter receiving a response I'm assuming the problem is with the bitmap of the outgoing message and the switch is rejecting the message and not sending a response?

**Comment by vamsikiranreddygithub** [comment] 2021-02-25 09:28
Below is the request configuration in Jmeter.

<isomsg direction="outgoing">
  
  <field id="0" value="0200"/>
  <field id="2" value="1107001009551457076"/>
  <field id="3" value="900000"/>
  <field id="4" value="000000001000"/>
  <field id="7" value="0225134920"/>
  <field id="11" value="000459"/>
  <field id="12" value="134920"/>
  <field id="13" value="0225"/>
  <field id="18" value="4814"/>
  <field id="22" value="019"/>
  <field id="25" value="05"/>
  <field id="32" value="111106"/>
  <field id="37" value="144959378033"/>
  <field id="41" value="BOS43210"/>
  <field id="42" value="BOS919876543210"/>
  <field id="43" value="BOSSPTA                  MOB9876543210IN"/>
  <field id="49" value="356"/>
  <field id="102" value="119876543210"/>
  <field id="120" value="00100245002003MOB045011NPCIBOSSP2A04900312305001711060019876543210051006P2AMOB056003MOB"/>
</isomsg>



The first line in the above HEX message, bitmap is not converted properly

**Comment by vamsikiranreddygithub** [comment] 2021-02-25 09:30
Sorry, unable to paste the code here. 
`<isomsg direction="outgoing">
  
  <field id="0" value="0200"/>
  <field id="2" value="1107001009551457076"/>
  <field id="3" value="900000"/>
  <field id="4" value="000000001000"/>
  <field id="7" value="0225134920"/>
  <field id="11" value="000459"/>
  <field id="12" value="134920"/>
  <field id="13" value="0225"/>
  <field id="18" value="4814"/>
  <field id="22" value="019"/>
  <field id="25" value="05"/>
  <field id="32" value="111106"/>
  <field id="37" value="144959378033"/>
  <field id="41" value="BOS43210"/>
  <field id="42" value="BOS919876543210"/>
  <field id="43" value="BOSSPTA                  MOB9876543210IN"/>
  <field id="49" value="356"/>
  <field id="102" value="119876543210"/>
  <field id="120" value="00100245002003MOB045011NPCIBOSSP2A04900312305001711060019876543210051006P2AMOB056003MOB"/>
</isomsg>

`

**Comment by vamsikiranreddygithub** [comment] 2021-02-25 09:35
![image](https://user-images.githubusercontent.com/79631431/109133130-ab626580-777a-11eb-85cb-e0abfc458e2c.png)

![image](https://user-images.githubusercontent.com/79631431/109133209-c59c4380-777a-11eb-9b85-92a947c94332.png)

Attached is the request and HEX message. First line in HEX message is the problem.
Please help in resolving the issue

**Comment by tilln** [comment] 2021-02-25 14:25
Would you mind being more specific as to what is actually wrong with the message? What are you expecting in the first line?

I'm guessing you expect the Bitmap to be ASCII encoded, i.e. there to be hex characters where your red rectangle is?

Have you tried changing your packager configuration? Are you using an ASCII or binary Bitmap, `IFA_BITMAP` vs. `IFB_BITMAP`, e.g. 

```
  <isofield
      id="1"
      length="16"
      name="BIT MAP"
      class="org.jpos.iso.IFA_BITMAP"/>
```

**Comment by vamsikiranreddygithub** [comment] 2021-02-25 14:40
We are using binary bitmap.
org.jpos.iso.IFB_BITMAP.
Let we try with ASCII and see if its working.
Thanks.

**Comment by vamsikiranreddygithub** [comment] 2021-02-26 11:01
Hi Tilln,
We have tried with ASCII and Binary but same result. Bitmap is the issue.
Any help on this please.

**Comment by tilln** [comment] 2021-02-27 01:05
@vamsikiranreddygithub 

Again, please be more specific. I have no idea what you are expecting.
Nor can I attempt to reproduce your issue without knowing your packager config.
You should clearly state the expected vs. the actual value (applies to any bug report).
If you can't provide this information I'm going got close this issue.

**Comment by vamsikiranreddygithub** [comment] 2021-03-01 10:21
@tilln 
Sorry for providing minimal details. Below are the complete details.

Bitmap configuration:
 isofield
      id="1"
      length="16"
      name="BIT MAP"
      class="org.jpos.iso.IFB_BITMAP"

We have also tried with length='8'

Expected Result:
![ExpectedResult](https://user-images.githubusercontent.com/79631431/109483104-d6172b80-7aa4-11eb-805a-6668ec1e4e6f.png)

Actual Result:
![Actualresult](https://user-images.githubusercontent.com/79631431/109483143-e3341a80-7aa4-11eb-9290-ede3a2de1736.png)
Provided the Expected result vs Actual result in the snapshots above highlighting the difference.

ISO8583 XML Config File
[iso87ascii.zip](https://github.com/tilln/jmeter-iso8583/files/6060762/iso87ascii.zip)

Please provide a solution for this.

**Comment by tilln** [comment] 2021-03-02 07:59
What encoding is this supposed to be?
The binary bitmap value `F2 38 44 81 08 E0 80 00 00 00 00 00 04 00 01 00` is correct.

**Closed** 2021-03-20 19:09 UTC
Labels: more-information-needed
