### ISSUE TITLE
Issue in ARQC Generation for CVN18/22

### ISSUE THREAD

**Issue by ManojhM-1530** [tilln/jmeter-iso8583#103] opened 2024-09-10 12:49 UTC
Hi @tilln,

While generating ARQC using the ISO8583 Crypto PreProcessor (ISO-8583 Version 1.3), I am able to generate an ARQC value, but we are getting declined error message due to ARQC. However, when I generate the ARQC using [online tool](https://paymentcardtools.com/arqc-calculators/cvn18), the value is correct, and I receive a successful response. I have attached the reference screenshots for your review. please note that we need to generate ARQC with CVN18/22.

Could you please assist me in resolving this issue? Is there any configuration that needs to be adjusted on my side?

*Note: Card number and key values have been masked.

Generated using online tool:

![image](https://github.com/user-attachments/assets/d5ff2034-f97e-434a-a944-892a52585b88)

Generated Using ISO-8583 pre processor:

![image](https://github.com/user-attachments/assets/4d0de729-2a85-45a8-9107-62fff755b273)

![image](https://github.com/user-attachments/assets/3214ea45-bd47-45c6-922b-125cba1723de)

**Comment by tilln** [comment] 2024-09-11 00:25
Hi @ManojhM-1530 

Thanks for reporting this issue.

I suspect it is caused by incorrect padding of the ARQC input data.

Could you please enter the value `80` in the "Padding (hex)" field and try again?

**Comment by ManojhM-1530** [comment] 2024-09-11 04:54
Hi @tilln,

Thank you for the advice. I added `80` in the "Padding (hex)" and generated the ARQC value and it worked for me. 

Once again Thank you for the quick response.

**Comment by tilln** [comment] 2024-09-11 05:34
The user should not have to provide the padding or even know what padding method to apply.

Ideally, the [`CryptogramDataBuilder`](https://github.com/jpos/jPOS/blob/v2_1_8/jpos/src/main/java/org/jpos/emv/cryptogram/CryptogramDataBuilder.java) or [`CryptogramSpec`](https://github.com/jpos/jPOS/blob/v2_1_8/jpos/src/main/java/org/jpos/emv/cryptogram/CryptogramSpec.java) should take care of that.

In fact, a padding option has been [introduced](https://github.com/jpos/jPOS/pull/577) but will only be released with [jPOS v.2.1.10](https://github.com/jpos/jPOS/wiki/ChangeLog#jpos-2110-snapshot).
However, it does not consistently define the method to use for all cryptogram versions (only [CPA](https://github.com/jpos/jPOS/blob/d1f202f65353b4ea52f8347e32424dbdc8c35ca6/jpos/src/main/java/org/jpos/emv/cryptogram/CPACryptogram.java#L14)).

**Closed as completed** 2024-11-26 02:40 UTC
Labels: enhancement
